pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// TODO: Find a way to move this to gradle.properties/build.gradle without errors
// Must match MOD_ID in HardenedGlass.kt
rootProject.name = 'hardenedglass'
